# Generated by Django 3.2.6 on 2021-08-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepost',
            name='description',
            field=models.TextField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='image',
            field=models.ImageField(default='', upload_to='static/uploads/images'),
        ),
    ]
